spring.application.name=morningpage

# 서버 설정
server.port=8080

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 로그
logging.level.org.hibernate.SQL=DEBUG

# 활성 프로파일
spring.profiles.active=local

# 세션 설정
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax